### ISSUE TITLE
Fix outbreak icon

### ISSUE THREAD

**Issue by pmandler-umass** [UMassCDS/avianfluapp#48]
The outbreak location icon shows fine locally, but does not work well with Amplify.
By using a local icon, it will also mean that we can change the colors if we choose.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the OutbreakPoints component to use a local icon for outbreak locations instead of relying on an external source. This should resolve the issue with the icon not displaying correctly on Amplify.

You can review changes in this commit: https://github.com/mnmnk43434/UMassCDS-avianfluapp-48/commit/8ab2f45a91c90241e087177cedd040a27b8d01cb.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by pmandler-umass** [comment]
worked only locally.

**Comment by pmandler-umass** [comment]
Fully fixed with #51
